### ISSUE TITLE
Neither the test file is working.. 

### ISSUE THREAD

**Issue by lucagianneschi** [andrewscofield/parse.com-php-library#57] opened 2012-12-13 09:11 UTC
I tried to copy and past the test file with the following code:

$testUser = new parseUser;
$testUser->username = "stefano_php";
$testUser->password = "pippo";
$user = $testUser->signup();

This is what I get as response..

  Notice: Trying to get property of non-object in D:\EasyPHP-12.1\www\jamyourself\lib.parse.php\parse.php on line 174

Notice: Trying to get property of non-object in D:\EasyPHP-12.1\www\jamyourself\lib.parse.php\parse.php on line 174

Fatal error: Uncaught ParseLibraryException: [0]: thrown in D:\EasyPHP-12.1\www\jamyourself\lib.parse.php\parse.php on line 167

I can't use this library at all, any suggestion on how to fix this stuff? Or is anyone guessing what am I doing wrong???

**Comment by andrewscofield** [comment] 2012-12-13 16:22
Are you downloading the entire library also are you on the latest version?

**Comment by lucagianneschi** [comment] 2012-12-17 08:20
Yea, I downloaded the latest version of the library here from Github, I'm currently using easyphp and all the curl libraries are correctly running.. I just want to work remotely, without the needing to upload through FTP on my server... Maybe there a compatibility issue with Windows 8 and easyphp, anyone reported any bug for this stuff??

**Comment by lucagianneschi** [comment] 2012-12-17 15:32
Da wp avevo messo 4 classi ok? Classe e superclasse è solo una definizione Inter nos, perché tutte le classi sono uguali a livello di db e di codice, superclasse per me è un contenitore, infatti sia album foto che album brani hanno una property array dove ci vanno foto e brani. Quindi se ok per fare 2 album distinti è come avevo scritto nel wp. Non credo che stiamo dicendo 2 cose diverse, credo solo che non ci stiamo capendo. Per la data io direi che la data di creazione. Dell'oggetto è la data in cui si immette un brano o una foto e questo è createdAt, ma poi io metterei una data che è la data in cui l'utente ha fatto il brano o scattato la foto. Torna?

Luca

Il giorno 17/dic/2012, alle ore 13:59, StefanoJ notifications@github.com ha scritto:

**Comment by joetech** [comment] 2012-12-27 14:08
I had a similar issue at line 178.  The problem is that you're not getting a "200" response from your request, so it tries to throw an error.  Then that line in the code is expecting $error (parsed json response) to be an object.  Instead the response is "FALSE", so it bombs.  I changed it to the following to work properly for errors, but you (me, too) still need to figure out why the query fails.

`if ($response) {
    $this->throwError($error->error,$error->code);
} else {
    $this->throwError($response,$responseCode);
}`

Additionally, my "response code 0" issue was resolved with this:
http://stackoverflow.com/questions/4570973/anything-wrong-with-my-curl-code-http-status-of-0

**Comment by andrewscofield** [comment] 2012-12-27 20:20
I wasn't aware that parse.com api ever returned a "FALSE", I wonder if this is new? Or maybe its something PHP/curl is doing?

The reason I did it the way I did was to make it easier to figure out why a query was failing. While doing some testing I also found it to be helpful to uncomment line 103 and print the results to screen. Is this where you are getting "FALSE?

**Comment by joetech** [comment] 2012-12-27 20:31
Yes, but I believe it was a result of curl failing with ssh.  The parseRestClient just doesn't seem to handle curl failure, I think.

**Comment by andrewscofield** [comment] 2012-12-27 21:38
yea, I think you're right. I'll figure out some ways to test or curl and php compatibility and just throw some errors up front if the server can't handle the library. Maybe I'll find some ways around using curl? Doubt it.

**Closed as completed** 2013-02-20 08:16 UTC
Labels: fix
